# Dockerfile
FROM ryht/blankon:rote
RUN apt-get update && apt-get upgrade -y && apt-get install -y \ 
    build-essential \ 
    curl \ 
    devscripts \ 
    equivs \ 
    git-buildpackage \ 
    git \ 
    lsb-release \ 
    make \ 
    openssh-client \ 
    pristine-tar \ 
    rake \ 
    rsync \ 
    ruby \ 
    ruby-dev \ 
    rubygems \ 
    wget
CMD ["/bin/bash"]
